---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: ticketer
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: ticketer
        tier: backend
        track: stable
    spec:
      containers:
        - name: ticketer
          image: 'aueangpanit/main-ticketer-service:latest'
          ports:
            - name: http
              containerPort: 8080
