---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: ticketer
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: ticketer
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "aueangpanit/ticketer-client:latest"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]