---
- hosts: all
  become: true
  tasks:
    - name: 'Install curl'
      apt:
        name: curl
        state: latest
        update_cache: true

# - hosts: web
#   become: true
#   tasks:
#     - name: 'Install nginx'
#       apt:
#         name: nginx
#         state: latest
#         update_cache: true
#     - name: 'Check if nginx is running'
#       service:
#         name: nginx
#         state: started

- hosts: jenkins
  become: true
  tasks:
    - name: 'Install nodejs'
      apt:
        name: nodejs
        state: latest
        update_cache: true  
    - name: 'Install npm'
      apt:
        name: npm
        state: latest
        update_cache: true
    - name: 'Install Docker'
      script: install_docker.sh
    - name: 'Transfer jenkins.sh script'
      copy: src=./jenkins.sh dest=/home/ mode=0777 
    - name: 'Install Jenkins'
      script: install_jenkins.sh
  